import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    // remはHTMLのフォントに対するサイズになる。HTMLのフォントサイズはデフォルトで16px。0.5remは16 * 0.5 = 8pxを意味している。
    <div className="flex min-h-screen flex-col items-center justify-center py-0 px-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello Next.js</h1>

      {/**
      <footer className={styles.footer}>
      <a
      href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
      target="_blank"
      rel="noopener noreferrer"
      >
      Powered by{' '}
      <span className={styles.logo}>
      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </span>
      </a>
      </footer>
    */}
    </div>
  );
}
